spring.application.name=lucaflix




server.port=8080
server.address=0.0.0.0









# JWT Configuration
app.jwt-secret=dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3JqYXZhYXBpaWFtdXNpbmdzcHJpbmdib290cmVzdGFwaTIwMjU=
app.jwt-expiration-milliseconds=86400000

# CORS Configuration - Corrigido
cors.allowed-origins=https://lucaflix.com,http://localhost:5173,http://localhost:5174,http://localhost:*,https://lucasflix.netlify.app,https://js.stripe.com,https://hooks.stripe.com
#cors.allowed-origins=http://46.136.25.252:*,http://46.136.*:3000,http://46.136.*.*,http://46.*.*.*,https://lucaflix.com,http://localhost:5173,http://localhost:5174,https://lucaflix.netlify.app,https://js.stripe.com,https://hooks.stripe.com


# DATABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://ep-ancient-credit-a8t1wp4v-pooler.eastus2.azure.neon.tech/neondb?user=neondb_owner&password=npg_j3pXuYLtkb1v&sslmode=require
spring.datasource.username=neondb
spring.datasource.password=npg_j3pXuYLtkb1v
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
debug=false

# Admin Configuration
admin.email=${INIT_EMAIL}
admin.password=${INIT_PASSWORD}
admin.firstname=${INIT_LAST_NAME}
admin.lastname=${INIT_FIRST_NAME}
admin.username=${INIT_USERNAME}



spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.pool-name=LucaflixHikariCP








#
## Logging Configuration
#logging.level.org.springframework.security=DEBUG
#logging.level.com.lucaflix=DEBUG
#logging.level.com.lucaflix.security=DEBUG
#
#

app.base-url=${URL_SITEMAP}
