spring.application.name=lucaflix

# CORS Configuration
cors.allowed-origins=https://citavip.site,http://localhost:5173,http://localhost:5174/,https://citavip.netlify.app,https://*.netlify.app,https://*.stripe.com,https://checkout.stripe.com,https://dashboard.stripe.com

# Stripe Configuration
stripe.api.key=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
stripe.api.key.public=pk_live_51Qqi7RBiO40P3fMh9zLPR05q2j6eMpnvUSZ3crzmiY2CmREBLali1YiEyNOe1goctDNcPendLC4cJ8igcn4un8pt00KKbEGBaO
stripe.webhook.secret=whsec_fqkOrmYK01tX6A0rPe64leQL06ouvlSr

# JWT Configuration
app.jwt-secret=dGhpc2lzYXZlcnlzZWN1cmVzZWNyZXRrZXlmb3JqYXZhYXBpaWFtdXNpbmdzcHJpbmdib290cmVzdGFwaTIwMjU=
app.jwt-expiration-milliseconds=86400000




# DATABASE (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=devlucas
spring.datasource.password=1234567890
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true






# Logging Configuration
logging.level.org.springframework.security=DEBUG
logging.level.com.lucaflix=DEBUG
logging.level.com.lucaflix.security=DEBUG